// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAkrfMDicLF5DuZbQ_Mi1qkQDjJv1EkTE',
    appId: '1:763781856186:web:bb8bfbe08e2e37f47dfb83',
    messagingSenderId: '763781856186',
    projectId: 'crud-flutter-f8c3b',
    authDomain: 'crud-flutter-f8c3b.firebaseapp.com',
    storageBucket: 'crud-flutter-f8c3b.firebasestorage.app',
    measurementId: 'G-YMWM8L93WZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAafxQkyjBU57yjAxvvuDC7YWBtkvTaEn4',
    appId: '1:763781856186:android:de4cd06f4186e9697dfb83',
    messagingSenderId: '763781856186',
    projectId: 'crud-flutter-f8c3b',
    storageBucket: 'crud-flutter-f8c3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4Ddj_5Y2z_uGykzqDlWi0-9BmBealI1Y',
    appId: '1:763781856186:ios:e56e62ba7b05bfae7dfb83',
    messagingSenderId: '763781856186',
    projectId: 'crud-flutter-f8c3b',
    storageBucket: 'crud-flutter-f8c3b.firebasestorage.app',
    iosBundleId: 'com.example.odoy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4Ddj_5Y2z_uGykzqDlWi0-9BmBealI1Y',
    appId: '1:763781856186:ios:e56e62ba7b05bfae7dfb83',
    messagingSenderId: '763781856186',
    projectId: 'crud-flutter-f8c3b',
    storageBucket: 'crud-flutter-f8c3b.firebasestorage.app',
    iosBundleId: 'com.example.odoy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAkrfMDicLF5DuZbQ_Mi1qkQDjJv1EkTE',
    appId: '1:763781856186:web:49f4ac3023f53cc27dfb83',
    messagingSenderId: '763781856186',
    projectId: 'crud-flutter-f8c3b',
    authDomain: 'crud-flutter-f8c3b.firebaseapp.com',
    storageBucket: 'crud-flutter-f8c3b.firebasestorage.app',
    measurementId: 'G-HRQFKN0QFM',
  );
}